name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & push backend
        run: |
          docker build -t test/backend:latest ./server
          docker push test/backend:latest
      - name: Build & push frontend
        run: |
          docker build -t test/frontend:latest ./client
          docker push test/frontend:latest